// The "boring businesses" universe -> UK SIC codes, grouped for the UI.
// Boring cash-flow businesses are the focus; property/land/CRE and tech are included.
export type TaxEntry = { label: string; group: string; sic: string[] };
export const TAXONOMY: Record<string, TaxEntry> = {
  // ---- Trades & construction ----
  plumbing_heating:   { label: 'Plumbing & heating', group: 'Trades & construction', sic: ['43220'] },
  electrical:         { label: 'Electrical contractors', group: 'Trades & construction', sic: ['43210'] },
  roofing:            { label: 'Roofing contractors', group: 'Trades & construction', sic: ['43910'] },
  scaffolding:        { label: 'Scaffolding & access', group: 'Trades & construction', sic: ['43991'] },
  groundworks:        { label: 'Groundworks & civil engineering', group: 'Trades & construction', sic: ['43120','42990'] },
  drainage:           { label: 'Drainage & utilities', group: 'Trades & construction', sic: ['42210','43999'] },
  demolition:         { label: 'Demolition & site clearance', group: 'Trades & construction', sic: ['43110'] },
  plastering:         { label: 'Plastering & drylining', group: 'Trades & construction', sic: ['43310'] },
  painting_decorating:{ label: 'Painting & decorating', group: 'Trades & construction', sic: ['43341'] },
  glazing:            { label: 'Glazing & windows', group: 'Trades & construction', sic: ['43342'] },
  joinery:            { label: 'Joinery & carpentry', group: 'Trades & construction', sic: ['43320','16230'] },
  flooring:           { label: 'Flooring contractors', group: 'Trades & construction', sic: ['43330'] },
  fencing:            { label: 'Fencing & gates', group: 'Trades & construction', sic: ['43290','43999'] },
  insulation:         { label: 'Insulation & energy efficiency', group: 'Trades & construction', sic: ['43290'] },
  steel_fabrication:  { label: 'Steel fabrication & welding', group: 'Trades & construction', sic: ['25110','25620','24330'] },
  shopfitting:        { label: 'Shopfitting & interiors', group: 'Trades & construction', sic: ['43320','31010'] },
  // ---- Facilities & maintenance ----
  facilities_mgmt:    { label: 'Facilities management', group: 'Facilities & maintenance', sic: ['81100'] },
  security_guarding:  { label: 'Security guarding', group: 'Facilities & maintenance', sic: ['80100'] },
  alarms_cctv:        { label: 'Alarms, CCTV & access control', group: 'Facilities & maintenance', sic: ['80200','43210'] },
  fire_protection:    { label: 'Fire protection & extinguishers', group: 'Facilities & maintenance', sic: ['84250','43220','80200'] },
  lift_maintenance:   { label: 'Lift installation & maintenance', group: 'Facilities & maintenance', sic: ['43290','33120'] },
  air_conditioning:   { label: 'Air conditioning & refrigeration', group: 'Facilities & maintenance', sic: ['43220'] },
  water_hygiene:      { label: 'Water hygiene & legionella', group: 'Facilities & maintenance', sic: ['71200','81299'] },
  landscaping:        { label: 'Landscaping & grounds maintenance', group: 'Facilities & maintenance', sic: ['81300'] },
  tree_surgery:       { label: 'Tree surgery & arboriculture', group: 'Facilities & maintenance', sic: ['81300','02400'] },
  locksmiths:         { label: 'Locksmiths', group: 'Facilities & maintenance', sic: ['80200','95290'] },
  // ---- Cleaning & hygiene ----
  commercial_cleaning:{ label: 'Commercial cleaning', group: 'Cleaning & hygiene', sic: ['81210','81229'] },
  window_cleaning:    { label: 'Window cleaning', group: 'Cleaning & hygiene', sic: ['81221'] },
  specialist_cleaning:{ label: 'Specialist & industrial cleaning', group: 'Cleaning & hygiene', sic: ['81222','81229','81299'] },
  pest_control:       { label: 'Pest control', group: 'Cleaning & hygiene', sic: ['81291'] },
  commercial_laundry: { label: 'Commercial laundry & linen hire', group: 'Cleaning & hygiene', sic: ['96010'] },
  dry_cleaning:       { label: 'Dry cleaning', group: 'Cleaning & hygiene', sic: ['96010'] },
  washroom_services:  { label: 'Washroom & hygiene services', group: 'Cleaning & hygiene', sic: ['81299','38220'] },
  // ---- Waste & environmental ----
  skip_hire:          { label: 'Skip hire & waste collection', group: 'Waste & environmental', sic: ['38110'] },
  waste_treatment:    { label: 'Waste treatment & disposal', group: 'Waste & environmental', sic: ['38210','38220'] },
  recycling:          { label: 'Recycling & materials recovery', group: 'Waste & environmental', sic: ['38320','38310'] },
  tank_services:      { label: 'Tanker & liquid waste services', group: 'Waste & environmental', sic: ['37000','38120'] },
  // ---- Transport & logistics ----
  haulage:            { label: 'Haulage & freight', group: 'Transport & logistics', sic: ['49410'] },
  couriers:           { label: 'Couriers & last-mile delivery', group: 'Transport & logistics', sic: ['53201','53202'] },
  removals:           { label: 'Removals & relocation', group: 'Transport & logistics', sic: ['49420'] },
  self_storage:       { label: 'Self storage', group: 'Transport & logistics', sic: ['52103'] },
  warehousing:        { label: 'Warehousing & 3PL', group: 'Transport & logistics', sic: ['52102','52101'] },
  cold_storage:       { label: 'Cold storage', group: 'Transport & logistics', sic: ['52102'] },
  freight_forwarding: { label: 'Freight forwarding & customs', group: 'Transport & logistics', sic: ['52290'] },
  coach_hire:         { label: 'Coach & minibus operators', group: 'Transport & logistics', sic: ['49390','49319'] },
  taxi_fleets:        { label: 'Taxi & private hire fleets', group: 'Transport & logistics', sic: ['49320'] },
  // ---- Automotive ----
  mot_garages:        { label: 'MOT & vehicle repair garages', group: 'Automotive', sic: ['45200'] },
  tyre_fitting:       { label: 'Tyre fitting & exhausts', group: 'Automotive', sic: ['45200'] },
  bodyshops:          { label: 'Accident repair & bodyshops', group: 'Automotive', sic: ['45200'] },
  vehicle_recovery:   { label: 'Vehicle recovery', group: 'Automotive', sic: ['52219'] },
  car_wash_valeting:  { label: 'Car wash & valeting', group: 'Automotive', sic: ['45200'] },
  vehicle_rental:     { label: 'Vehicle & van rental', group: 'Automotive', sic: ['77110','77120'] },
  driving_schools:    { label: 'Driving schools', group: 'Automotive', sic: ['85530'] },
  parts_distribution: { label: 'Motor parts distribution', group: 'Automotive', sic: ['45310','45320'] },
  // ---- Property, land & real estate ----
  property_investment:{ label: 'Property investment (own & let)', group: 'Property, land & real estate', sic: ['68100','68209'] },
  commercial_letting: { label: 'Commercial real estate letting', group: 'Property, land & real estate', sic: ['68201','68209'] },
  property_mgmt:      { label: 'Property & block management', group: 'Property, land & real estate', sic: ['68320'] },
  letting_agents:     { label: 'Estate & letting agents', group: 'Property, land & real estate', sic: ['68310'] },
  property_development:{ label: 'Property development', group: 'Property, land & real estate', sic: ['41100','41202'] },
  land_promotion:     { label: 'Land trading & promotion', group: 'Property, land & real estate', sic: ['68100','42990'] },
  holiday_lets:       { label: 'Holiday lets & serviced accommodation', group: 'Property, land & real estate', sic: ['55209','68209'] },
  caravan_parks:      { label: 'Caravan & holiday parks', group: 'Property, land & real estate', sic: ['55300'] },
  storage_containers: { label: 'Container storage & yards', group: 'Property, land & real estate', sic: ['52103','68209'] },
  surveying:          { label: 'Surveying & valuation', group: 'Property, land & real estate', sic: ['68310','71129'] },
  // ---- Health & care ----
  care_homes:         { label: 'Care homes (elderly)', group: 'Health & care', sic: ['87100','87300'] },
  domiciliary_care:   { label: 'Domiciliary & home care', group: 'Health & care', sic: ['88100'] },
  supported_living:   { label: 'Supported living & specialist care', group: 'Health & care', sic: ['87200','87900'] },
  dental_practices:   { label: 'Dental practices', group: 'Health & care', sic: ['86230'] },
  opticians:          { label: 'Opticians', group: 'Health & care', sic: ['47782','86900'] },
  pharmacies:         { label: 'Pharmacies', group: 'Health & care', sic: ['47730'] },
  physio_clinics:     { label: 'Physio & allied health clinics', group: 'Health & care', sic: ['86900'] },
  medical_staffing:   { label: 'Medical & care staffing', group: 'Health & care', sic: ['78200','86900'] },
  // ---- Children & education ----
  nurseries:          { label: 'Children’s nurseries', group: 'Children & education', sic: ['85100','88910'] },
  childrens_services: { label: 'Children’s residential care', group: 'Children & education', sic: ['87900'] },
  training_providers: { label: 'Training & apprenticeship providers', group: 'Children & education', sic: ['85590','85320'] },
  tuition:            { label: 'Tuition & education services', group: 'Children & education', sic: ['85590','85600'] },
  // ---- Food & drink ----
  food_manufacturing: { label: 'Food manufacturing', group: 'Food & drink', sic: ['10890','10850','10710'] },
  bakeries:           { label: 'Bakeries', group: 'Food & drink', sic: ['10710','47240'] },
  butchers_meat:      { label: 'Meat processing & butchery', group: 'Food & drink', sic: ['10110','10130','47220'] },
  contract_catering:  { label: 'Contract catering', group: 'Food & drink', sic: ['56290','56210'] },
  event_catering:     { label: 'Event catering', group: 'Food & drink', sic: ['56210'] },
  vending:            { label: 'Vending & micro markets', group: 'Food & drink', sic: ['47990'] },
  food_wholesale:     { label: 'Food & drink wholesale', group: 'Food & drink', sic: ['46390','46310','46320'] },
  // ---- Leisure & hospitality ----
  gyms:               { label: 'Gyms & fitness', group: 'Leisure & hospitality', sic: ['93130'] },
  golf_leisure:       { label: 'Golf & outdoor leisure', group: 'Leisure & hospitality', sic: ['93110','93199'] },
  soft_play:          { label: 'Soft play & family entertainment', group: 'Leisure & hospitality', sic: ['93290'] },
  garden_centres:     { label: 'Garden centres', group: 'Leisure & hospitality', sic: ['47760'] },
  hotels_bnb:         { label: 'Hotels & guest houses', group: 'Leisure & hospitality', sic: ['55100'] },
  // ---- Distribution & wholesale ----
  builders_merchants: { label: 'Builders & timber merchants', group: 'Distribution & wholesale', sic: ['46730'] },
  electrical_wholesale:{ label: 'Electrical wholesale', group: 'Distribution & wholesale', sic: ['46690','46430'] },
  plumbing_supplies:  { label: 'Plumbing & heating supplies', group: 'Distribution & wholesale', sic: ['46740'] },
  janitorial_supplies:{ label: 'Janitorial & packaging supplies', group: 'Distribution & wholesale', sic: ['46499','46760'] },
  workwear_ppe:       { label: 'Workwear & PPE distribution', group: 'Distribution & wholesale', sic: ['46420','46160'] },
  industrial_distribution:{ label: 'Industrial & engineering supplies', group: 'Distribution & wholesale', sic: ['46690','46620'] },
  ecommerce:          { label: 'E-commerce & online retail', group: 'Distribution & wholesale', sic: ['47910'] },
  // ---- Manufacturing & industrial ----
  precision_machining:{ label: 'Precision machining & toolmaking', group: 'Manufacturing & industrial', sic: ['25620','25730'] },
  injection_moulding: { label: 'Plastics & injection moulding', group: 'Manufacturing & industrial', sic: ['22290','22220'] },
  packaging_mfg:      { label: 'Packaging manufacture', group: 'Manufacturing & industrial', sic: ['17211','17219','22220'] },
  signage:            { label: 'Signage & display', group: 'Manufacturing & industrial', sic: ['25990','73110'] },
  commercial_printing:{ label: 'Commercial printing & labels', group: 'Manufacturing & industrial', sic: ['18110','18121','18129'] },
  joinery_mfg:        { label: 'Joinery & furniture manufacture', group: 'Manufacturing & industrial', sic: ['16230','31010','31090'] },
  equipment_hire:     { label: 'Plant & tool hire', group: 'Manufacturing & industrial', sic: ['77320','77390','77290'] },
  // ---- Professional services ----
  accountancy:        { label: 'Accountancy practices', group: 'Professional services', sic: ['69201','69202','69203'] },
  bookkeeping_payroll:{ label: 'Bookkeeping & payroll bureaus', group: 'Professional services', sic: ['69202','82990'] },
  insurance_brokers:  { label: 'Insurance brokers', group: 'Professional services', sic: ['66220'] },
  recruitment:        { label: 'Recruitment agencies', group: 'Professional services', sic: ['78100','78109','78200'] },
  utilities_brokers:  { label: 'Utilities & cost consultancies', group: 'Professional services', sic: ['74909','70229'] },
  funeral_services:   { label: 'Funeral directors', group: 'Professional services', sic: ['96030'] },
  // ---- Pets & animals ----
  vets:               { label: 'Veterinary practices', group: 'Pets & animals', sic: ['75000'] },
  kennels_catteries:  { label: 'Kennels, catteries & pet care', group: 'Pets & animals', sic: ['96090','01620'] },
  pet_supplies:       { label: 'Pet food & supplies', group: 'Pets & animals', sic: ['47760','46380'] },
  // ---- Agriculture & rural ----
  agri_contracting:   { label: 'Agricultural contracting', group: 'Agriculture & rural', sic: ['01610'] },
  agri_supplies:      { label: 'Agricultural machinery & supplies', group: 'Agriculture & rural', sic: ['46610','28302'] },
  equestrian:         { label: 'Equestrian & livery', group: 'Agriculture & rural', sic: ['01430','93199'] },
  // ---- Tech & digital ----
  saas_software:      { label: 'Software & SaaS', group: 'Tech & digital', sic: ['62012','58290'] },
  it_msp:             { label: 'IT support & managed services', group: 'Tech & digital', sic: ['62020','62090'] },
  hosting_data:       { label: 'Hosting & data centres', group: 'Tech & digital', sic: ['63110','63120'] },
  cyber_security:     { label: 'Cyber security services', group: 'Tech & digital', sic: ['62020','62090','80200'] },
  digital_agencies:   { label: 'Digital & marketing agencies', group: 'Tech & digital', sic: ['73110','62012'] },
  telecoms:           { label: 'Telecoms & connectivity', group: 'Tech & digital', sic: ['61900','61100'] },
  fieldtech_iot:      { label: 'Field tech, EPOS & IoT services', group: 'Tech & digital', sic: ['62090','33120','95110'] },
};
