// TEST-MODE COPY of acq-billing - generated by supabase/functions/_test/make-test-copies.sh.
// Differences from the original: reads oi_config.stripe_test_secret_key (Stripe sandbox),
// caches sandbox products/prices under stripe_test_* keys, and redirects to localhost:5173.
// Never used by production; the live functions and stripe_secret_key are untouched.
// =============================================================================
// acq-billing v3 — Stripe checkout + customer portal + IN-PLACE PLAN CHANGES.
// Monthly: analyst £99 · originator £299 · team £749.
// ANNUAL: pay for 10 months, get 12 — analyst £990 · originator £2,990 · team £7,490.
// v3: if the org already has a live subscription, checkout SWAPS the price on
// the existing subscription (prorated) instead of creating a second one.
// Products/prices bootstrapped on first use, cached in oi_config.
// =============================================================================
import postgres from 'npm:postgres@3.4.5';
import { createClient } from 'npm:@supabase/supabase-js@2';
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;
const DB_URL = Deno.env.get('SUPABASE_DB_URL')!;
const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods': 'POST, OPTIONS' };
const json = (b: unknown, s = 200) => new Response(JSON.stringify(b), { status: s, headers: { ...cors, 'Content-Type': 'application/json' } });

const PLANS: Record<string, { label: string; amount: number; annual: number }> = {
  analyst: { label: 'Officially Invested AI — Analyst', amount: 9900, annual: 99000 },
  originator: { label: 'Officially Invested AI — Originator', amount: 29900, annual: 299000 },
  team: { label: 'Officially Invested AI — Team', amount: 74900, annual: 749000 },
};

async function stripe(key: string, path: string, params?: Record<string, string>) {
  const r = await fetch(`https://api.stripe.com/v1/${path}`, {
    method: params ? 'POST' : 'GET',
    headers: { Authorization: `Bearer ${key}`, 'content-type': 'application/x-www-form-urlencoded' },
    body: params ? new URLSearchParams(params).toString() : undefined,
  });
  const j = await r.json();
  if (!r.ok) throw new Error(j?.error?.message ?? `stripe ${path} ${r.status}`);
  return j;
}

async function ensurePrice(sql: any, key: string, plan: string, annual: boolean): Promise<string> {
  const cacheKey = 'stripe_test_price_' + plan + (annual ? '_annual' : '');
  let priceId = (await sql`select value from public.oi_config where key=${cacheKey}`)[0]?.value;
  if (priceId) return priceId;
  let productId = (await sql`select value from public.oi_config where key=${'stripe_test_product_' + plan}`)[0]?.value;
  if (!productId) {
    const product = await stripe(key, 'products', { name: PLANS[plan].label, 'metadata[plan]': plan });
    productId = product.id;
    await sql`insert into public.oi_config (key, value) values (${'stripe_test_product_' + plan}, ${productId}) on conflict (key) do update set value=excluded.value`;
  }
  const price = await stripe(key, 'prices', {
    product: productId, currency: 'gbp',
    unit_amount: String(annual ? PLANS[plan].annual : PLANS[plan].amount),
    'recurring[interval]': annual ? 'year' : 'month',
    'metadata[plan]': plan, 'metadata[interval]': annual ? 'annual' : 'monthly',
  });
  await sql`insert into public.oi_config (key, value) values (${cacheKey}, ${price.id}) on conflict (key) do update set value=excluded.value`;
  return price.id;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });
  const sql = postgres(DB_URL, { prepare: false });
  const done = async (b: unknown, s = 200) => { await sql.end({ timeout: 5 }); return json(b, s); };
  try {
    const body = await req.json().catch(() => ({} as any));
    const action = body.action ?? 'checkout';

    const sb = createClient(SUPABASE_URL, ANON_KEY, { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } });
    const { data } = await sb.auth.getUser();
    if (!data?.user) return done({ error: 'unauthorised' }, 401);
    const mem = (await sql`select m.org_id, o.settings, o.name from acq.org_members m join acq.organizations o on o.id=m.org_id where m.user_id=${data.user.id} order by m.created_at limit 1`)[0];
    if (!mem) return done({ error: 'no workspace — complete signup first' }, 403);

    const key = (await sql`select value from public.oi_config where key='stripe_test_secret_key'`)[0]?.value;
    if (!key) return done({ error: 'not_configured', message: 'Payments are being switched on — email sandeep@officiallyinvested.com to upgrade today.' });

    if (action === 'checkout') {
      const plan = String(body.plan ?? '');
      const annual = body.interval === 'annual' || body.annual === true;
      if (!PLANS[plan]) return done({ error: 'unknown plan' }, 400);
      const priceId = await ensurePrice(sql, key, plan, annual);

      // Already subscribed? Swap the price on the existing subscription
      // (prorated by Stripe) instead of creating a second subscription.
      const existingSubId = mem.settings?.billing?.subscription_id;
      if (existingSubId) {
        try {
          const sub = await stripe(key, `subscriptions/${existingSubId}`);
          if (['active', 'trialing', 'past_due'].includes(sub.status)) {
            const itemId = sub.items?.data?.[0]?.id;
            if (itemId) {
              await stripe(key, `subscriptions/${existingSubId}`, {
                'items[0][id]': itemId,
                'items[0][price]': priceId,
                proration_behavior: 'create_prorations',
                'metadata[org_id]': mem.org_id,
                'metadata[plan]': plan,
                'metadata[interval]': annual ? 'annual' : 'monthly',
              });
              // customer.subscription.updated webhook applies the entitlement
              return done({ ok: true, changed: true, plan, interval: annual ? 'annual' : 'monthly', message: 'Plan changed. Stripe prorates the difference on your next invoice.' });
            }
          }
        } catch (_) { /* stale subscription id - fall through to fresh checkout */ }
      }

      const site = 'http://localhost:5173';
      const session = await stripe(key, 'checkout/sessions', {
        mode: 'subscription',
        'line_items[0][price]': priceId,
        'line_items[0][quantity]': '1',
        customer_email: data.user.email ?? '',
        client_reference_id: mem.org_id,
        'metadata[org_id]': mem.org_id,
        'metadata[plan]': plan,
        'metadata[interval]': annual ? 'annual' : 'monthly',
        'subscription_data[metadata][org_id]': mem.org_id,
        'subscription_data[metadata][plan]': plan,
        'subscription_data[metadata][interval]': annual ? 'annual' : 'monthly',
        allow_promotion_codes: 'true',
        success_url: `${site}/admin/origination?upgraded=${plan}`,
        cancel_url: `${site}/admin/origination?view=billing`,
      });
      return done({ ok: true, url: session.url });
    }

    if (action === 'portal') {
      const customer = mem.settings?.billing?.customer_id;
      if (!customer) return done({ error: 'no active subscription yet' }, 400);
      const session = await stripe(key, 'billing_portal/sessions', { customer, return_url: 'http://localhost:5173/admin/origination?view=billing' });
      return done({ ok: true, url: session.url });
    }

    return done({ error: `unknown action ${action}` }, 400);
  } catch (e) {
    try { await sql.end({ timeout: 5 }); } catch (_) { /* noop */ }
    return json({ error: String(e).slice(0, 300) }, 500);
  }
});
