#!/usr/bin/env bash
# Regenerates the *-test copies of the billing functions from the originals.
# Run from supabase/functions after changing acq-billing / acq-credits / acq-stripe-webhook.
set -euo pipefail
cd "$(dirname "$0")/.."
for f in acq-billing acq-credits acq-stripe-webhook; do
  mkdir -p "$f-test"
  {
    echo "// TEST-MODE COPY of $f - generated by supabase/functions/_test/make-test-copies.sh."
    echo "// Differences from the original: reads oi_config.stripe_test_secret_key (Stripe sandbox),"
    echo "// caches sandbox products/prices under stripe_test_* keys, and redirects to localhost:5173."
    echo "// Never used by production; the live functions and stripe_secret_key are untouched."
    sed -e "s/'stripe_secret_key'/'stripe_test_secret_key'/g" \
        -e "s/'stripe_price_' + plan/'stripe_test_price_' + plan/g" \
        -e "s/'stripe_product_' + plan/'stripe_test_product_' + plan/g" \
        -e "s#const site = 'https://www.officiallyinvested.com';#const site = 'http://localhost:5173';#" \
        -e "s#https://www.officiallyinvested.com/admin/origination?view=billing&topup=done#http://localhost:5173/admin/origination?view=billing\&topup=done#" \
        -e "s#return_url: 'https://www.officiallyinvested.com/admin/origination?view=billing'#return_url: 'http://localhost:5173/admin/origination?view=billing'#" \
        -e "s#cancel_url: 'https://www.officiallyinvested.com/admin/origination?view=billing'#cancel_url: 'http://localhost:5173/admin/origination?view=billing'#" \
        "$f/index.ts"
  } > "$f-test/index.ts"
done
echo "regenerated acq-billing-test acq-credits-test acq-stripe-webhook-test"
